name: Push to Docker Hub

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 6" # 00:00 on Saturdays

jobs:
  push:
    strategy:
      fail-fast: false
      matrix:
        image: [builder, app]
        ruby: ["3.2.1"]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: docker/setup-buildx-action@v2

      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: docker/build-push-action@v4
        with:
          context: ${{ matrix.image }}
          build-args: |
            RUBY_VERSION=${{ matrix.ruby }}
          tags: railbarge/${{ matrix.image }}:ruby-${{ matrix.ruby }}
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
